version: '3'
services:
    postgres:
        image: postgres
        volumes:
          - .docker/postgresql:/var/lib/postgresql/data
        ports:
          - '5432:5432'
        environment:
          - POSTGRES_DB={{db-name}}
          - POSTGRES_USER={{db-username}}
          - POSTGRES_PASSWORD={{db-password}}
